authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import ManagerRegister, EngineerRegister, DoctorRegister
from .views import SignUpView
from med.views import JoinHospitalView, RequestJoinHospitalView
from django_email_verification import urls as email_urls
from django.conf.urls import include

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'authentication/login.html'), name ='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name ='logout'),
    path('register/', SignUpView.as_view(), name ='register'),
    path('manager-register/', ManagerRegister, name ='manager-register'),
    path('engineer-register/', EngineerRegister, name ='engineer-register'),
    path('doctor-register/', DoctorRegister, name ='doctor-register'),
    path('request-join-hospital/<int:hid>/<int:uid>/', RequestJoinHospitalView, name ='request-join-hospital'),
    path('join-hospital/<int:uid>/', JoinHospitalView, name ='join-hospital'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='change-password.html'), name ='password_change'),
    path('email/', include(email_urls))

   # reset > done > confirm > done > complete

]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import home, profile, update_profile
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from authentication.forms import EmailValidationOnForgotPassword, CustomSetPasswordForm
from django.conf.urls import url


urlpatterns = [
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(form_class = CustomSetPasswordForm), {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('profile/', profile, name='profile'),
    path('update-profile', update_profile, name='update'),
    path('auth/', include('authentication.urls')),
    path('med/', include('med.urls')), 
    path('workflow/', include('workflow.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

med/urls.py
from django.urls import path
from med.views import (CreateHospitalView, 
                        HospitalDetailsView, 
                        SearchHospitalResultsView, 
                        SearchHospitalView, 
                        EquipmentListView, 
                        EquipmentDetailsView,
                        NotificationsListView,
                        DepartmentListView, 
                        List_Create_CompanyView,
                        DepartmentDetailsView,
                        PreApprovedEquipmentDetails, 
                        generate_PDF,
                        upload_json,
                        EquipmentProcedureView,
                        welcome)

urlpatterns = [
    path('register_hospital/', CreateHospitalView.as_view(), name='register-hospital' ),
    path('search/', SearchHospitalView.as_view(), name ='hospital-search'),
    path('search-results/', SearchHospitalResultsView.as_view(), name ='hospital-search-results'),
    path('equipment-list/', EquipmentListView.as_view(), name ='equipment-list'),
    path('department-list/', DepartmentListView.as_view(), name ='department-list'),
    path('hospital-details/<int:pk>/', HospitalDetailsView.as_view(), name ='hospital-details'),
    path('equipment-details/<int:pk>/', EquipmentDetailsView.as_view(), name ='equipment-details'),
    path('equipment-procedure/<int:pk>/', EquipmentProcedureView.as_view(), name ='equipment-procedure'),

    path('pre-approved-equipment-details/<int:pk>/', PreApprovedEquipmentDetails.as_view(), name ='pre-approved-equipment-details'),
    path('department-details/<int:pk>/', DepartmentDetailsView.as_view(), name ='department-details'),
    path('list-notifications/', NotificationsListView.as_view(), name ='list-notifications'),
    path('list-create-company/', List_Create_CompanyView.as_view(), name ='list-create-company'),
    path('get-pdf/<int:pk>/', generate_PDF, name ='get-pdf'),
    path('upload-json/', upload_json, name ='upload-json'),
    path('welcome/', welcome, name ='welcome'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.urls import reverse, reverse_lazy
from django import forms

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()     
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):

    photo_user = models.ImageField(upload_to='photos', null = True , blank = True)
    
    class Types(models.TextChoices):
        MANAGER = "MANAGER", "manager"
        ENGINEER = "ENGINEER", "engineer"
        DOCTOR = "DOCTOR", "doctor"
    photo_user = models.ImageField(upload_to='photos', null = True , blank = True)
    
    email = models.EmailField(_('email address'), unique=True)
    type = models.CharField(_("Type"), max_length= 50, choices=Types.choices, default = Types.MANAGER)
    in_hospital = models.BooleanField(_("Currently registered in a hospital"), default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.utils.translation import gettext_lazy as _
from med.models import Department, Doctor, Engineer, Manager
from django_email_verification import send_email
from django.contrib.auth.forms import (PasswordResetForm, SetPasswordForm)
from .models import User
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)


class ManagerSignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Manager
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
    
    def save(self):
        user = super().save(commit=False)
        user.type = 'MANAGER'
        user.is_active = False
        user.save()
        send_email(user)
        return user

class EngineerSignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Engineer
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

        # department = forms.ModelChoiceField(
        #     queryset=Department.objects.all().distinct(),
        #     widget=forms.Select
        # )
    
    def save(self):
        user = super().save(commit=False)
        user.type = 'ENGINEER'
        user.is_active = False
        user.save()
        send_email(user)
        return user

class DoctorSignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Doctor
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
    
    def save(self):
        user = super().save(commit=False)
        user.type = 'DOCTOR'
        user.is_active = False
        user.save()
        send_email(user)
        return user


class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError("The email address you entered is not registered. Please enter registered email id")
        return email


class CustomSetPasswordForm(SetPasswordForm):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'password_notvalid': _("Password must of 8 Character which contain alphanumeric with atleast 1 special charater and 1 uppercase."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
            # Regix to check the password must contains sepcial char, numbers, char with upeercase and lowercase.
            regex = re.compile('((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{8,30})')
            if(regex.search(password1) == None):
                    raise forms.ValidationError(
                    self.error_messages['password_notvalid'],
                    code='password_mismatch',
                )

        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        email = self.user.email
        instance = User.objects.get(id=self.user.id)
        if not instance.first_login:
            instance.first_login = True
            instance.save()
        return self.user

authentication/views.py
from django.shortcuts import render, redirect
from .forms import ManagerSignUpForm, EngineerSignUpForm, DoctorSignUpForm
from django.views.generic import TemplateView, ListView
from med.models import Hospital
from django.contrib import messages


class SignUpView(TemplateView):
    template_name = 'authentication/register.html'

def ManagerRegister(request):
    if request.method == 'POST':
        form = ManagerSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'An Email has been sent, please confirm to log in..')
            return redirect('login')
    else:
        form = ManagerSignUpForm()
    return render(request, 'authentication/register_form.html', {'form' : form})

def EngineerRegister(request):
    if request.method == 'POST':
        form = EngineerSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'An Email has been sent, please confirm to log in..')
            return redirect('login')
    else:
        form = EngineerSignUpForm()
    return render(request, 'authentication/register_form.html', {'form' : form})

def DoctorRegister(request):
    if request.method == 'POST':
        form = DoctorSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'An Email has been sent, please confirm to log in..')
            return redirect('login')
    else:
        form = DoctorSignUpForm()
    return render(request, 'authentication/register_form.html', {'form' : form})

def ForgetPassword(request):
    if request.method == 'POST':
        form = CustomSetPasswordForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'An Email has been sent, please confirm to log in..')
            return redirect('login')
    else:
        form = CustomSetPasswordForm()
    return render(request, 'authentication/password_reset_form.html', {'form' : form})

#class SetPasswordForm 
# A form that lets a user change their password without entering the old password.

authentication/templates/authentication/login.html
{% load crispy_forms_tags %}
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Signin</title>
    <link href="{% static 'dashboard/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'dashboard/signin.css' %}" rel="stylesheet">
</head>

<body class="text-center">
    <form class="form-signin" method="POST">
        {% csrf_token %}
        <img class="mb-4" src="{% static 'dashboard/Untitled-1-01.png' %}" alt="" width="150" height="150">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        {{ form|crispy }}
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <div class="border-top pt-3">
            <small class="muted-text">
               Need an Account ? <a href="{% url 'register' %}" class="ml-2">Sign Up!</a> 
            </small>
        </div>
        <div class="border-top pt-3">
            <small class="muted-text">
                forget your password! <a href="{% url 'register' %}" class="ml-2">forget your password!</a> 
            </small>
        </div>
        <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
    </form>
</body>

</html>

authentication/templates/authentication/logout.html
{% extends "dashboard/base.html" %}

{% block content %}
<div class="content-section">
    <h2>You have been logged out!</h2>

    <div class="border-top pt-3">
        <small class="muted-text">
           Login again ? <a href="{% url 'login' %}" >Login</a> 
        </small>
    </div>
</div>

{% endblock content%}

authentication/templates/authentication/password_reset_complete.html
{% extends "dashboard/base.html" %}

{% block title %}Password reset complete{% endblock %}

{% block pagetitle %}Password reset complete{% endblock %}

{% block content %}
<p>Your password has been set.  You may go ahead and log in now.</p>
<p><a href="{% url 'login'%}">Log in>/a></p>
{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends "dashboard/base.html" %}

{% block title %}Password reset{% endblock %}

{% block pagetitle %}Password reset{% endblock %}

{% block content %}

{% if validlink %}
<p>Please enter your new password twice so we can verify you typed it in correctly.</p>
<form action="" method="post">
  <table>
    <tr>
      <td>{{ form.new_password1.errors }}<label for="id_new_password1">New password:</label></td>
      <td>{{ form.new_password1 }}</td>
    </tr>
    <tr>
      <td>{{ form.new_password2.errors }}<label for="id_new_password2">Confirm password:</label></td>
      <td>{{ form.new_password2 }}</td>
    </tr>
    <tr>
      <td></td>
      <td><input type="submit" value="Change my password" /></td>
    </tr>
  </table>
</form>
{% else %}
<h1>Password reset unsuccessful</h1>
<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
{% endif %}
{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends "dashboard/base.html" %}

{% block title %}Password reset successful{% endblock %}

{% block pagetitle %}Password reset successful{% endblock %}

{% block content %}
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>
{% endblock %}

authentication/templates/authentication/password_reset_email.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url django.contrib.auth.views.password_reset_confirm uidb36=uid, token=token %}
{% endblock %}

Your username, in case you've forgotten: {{ user.username }}

Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}

authentication/templates/authentication/password_reset_form.html
{% extends "dashboard/base.html" %}

{% block title %}Password reset{% endblock %}

{% block pagetitle %}Password reset{% endblock %}

{% block content %}
<p>Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one.</p>

<form action="" method="post">
    {% csrf_token %}
 {{ form.email.errors }}
<p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset my password" /></p>
</form>
{% endblock %}

authentication/templates/authentication/register.html
{% extends "dashboard/base.html" %}

{% block content %}
  
<h2>Sign up for a free account</h2>
<p class="lead">Select below the type of account you want to create</p>
<button class="btn"><a href="{% url 'manager-register' %}" class="btn btn-manager btn-primary" role="button">I'm a Manager</a></button>
<button class="btn"><a href="{% url 'engineer-register' %}" class="btn btn-engineer btn-primary" role="button">I'm an Engineer</a></button>
<button class="btn"><a href="{% url 'doctor-register' %}" class="btn btn-doctor btn-primary" role="button">I'm a Doctor</a></button>

{% endblock %}

authentication/templates/authentication/register_form.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="from-group">
            <legend class="border-bottom mb-4">Sign Up!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign up</button>
        </div>

    </form>

    <div class="border-top pt-3">
        <small class="muted-text">
           Already have An Account ? <a href="{% url 'login' %}" class="ml-2">Sign in</a> 
        </small>
    </div>
</div>
{% endblock %}