hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import home, profile, update_profile
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from authentication.forms import EmailValidationOnForgotPassword, CustomSetPasswordForm
from django.conf.urls import url


urlpatterns = [
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(form_class = CustomSetPasswordForm), {'template_name': 'registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('profile/', profile, name='profile'),
    path('update-profile', update_profile, name='update'),
    path('auth/', include('authentication.urls')),
    path('med/', include('med.urls')), 
    path('workflow/', include('workflow.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

med/urls.py
from django.urls import path
from med.views import (CreateHospitalView, 
                        HospitalDetailsView, 
                        SearchHospitalResultsView, 
                        SearchHospitalView, 
                        EquipmentListView, 
                        EquipmentDetailsView,
                        NotificationsListView,
                        DepartmentListView, 
                        List_Create_CompanyView,
                        DepartmentDetailsView,
                        PreApprovedEquipmentDetails, 
                        generate_PDF,
                        upload_json,
                        EquipmentProcedureView,
                        welcome)

urlpatterns = [
    path('register_hospital/', CreateHospitalView.as_view(), name='register-hospital' ),
    path('search/', SearchHospitalView.as_view(), name ='hospital-search'),
    path('search-results/', SearchHospitalResultsView.as_view(), name ='hospital-search-results'),
    path('equipment-list/', EquipmentListView.as_view(), name ='equipment-list'),
    path('department-list/', DepartmentListView.as_view(), name ='department-list'),
    path('hospital-details/<int:pk>/', HospitalDetailsView.as_view(), name ='hospital-details'),
    path('equipment-details/<int:pk>/', EquipmentDetailsView.as_view(), name ='equipment-details'),
    path('equipment-procedure/<int:pk>/', EquipmentProcedureView.as_view(), name ='equipment-procedure'),

    path('pre-approved-equipment-details/<int:pk>/', PreApprovedEquipmentDetails.as_view(), name ='pre-approved-equipment-details'),
    path('department-details/<int:pk>/', DepartmentDetailsView.as_view(), name ='department-details'),
    path('list-notifications/', NotificationsListView.as_view(), name ='list-notifications'),
    path('list-create-company/', List_Create_CompanyView.as_view(), name ='list-create-company'),
    path('get-pdf/<int:pk>/', generate_PDF, name ='get-pdf'),
    path('upload-json/', upload_json, name ='upload-json'),
    path('welcome/', welcome, name ='welcome'),
]

dashboard/models.py
from django.db import models
from authentication.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


    def __str__(self):
        return f'{self.user.username} Profile'

med/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from authentication.models import User
from django.contrib.auth.models import AbstractUser, BaseUserManager
import datetime



# from authentication.models import HospitalManager

class Hospital(models.Model):
    name = models.CharField(_("Hospital Name"), max_length = 225, unique=True)
    address = models.TextField(_("Hospital Address"), null=True)
    phone_num = models.IntegerField()
    manager = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('hospital-details', kwargs={'pk' : self.pk})


class Department(models.Model):
    name = models.CharField(_("Department Name"), max_length = 225)
    hospital = models.ForeignKey(Hospital, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name
    

class Equipment(models.Model):
    STATUS = (
        ('LIVE', _("LIVE")),
        ('DOWN', _("DOWN"))
    )
    status = models.CharField(_("Equipment Status"), max_length=50, choices=STATUS, default='LIVE')
    is_approved = models.BooleanField(_("Is approved by manager"), default=True)
    name = models.CharField(_("Equipment Name"), max_length = 225) #unique=True
    specs = models.TextField(_("Technical Specifications and Standards"))
    quantity = models.IntegerField()
    serial_num = models.IntegerField()
    manufacturer = models.CharField(_("Manufacturer"), null=True,max_length = 255)
    country = models.CharField(_("Country"), null=True,max_length = 225)
    model = models.CharField(_("Model"), null=True,max_length = 225)
    risk_level = models.CharField(_("Risk Level"), null=True,max_length = 225)
    eq_class = models.CharField(_("class"), null=True,max_length = 225)
    bio_code = models.CharField(_("BioCode"), null=True, max_length = 225)
    med_agent = models.CharField(_("Medical Agent"),null=True, max_length = 225)
    delivery_date = models.DateField(_("Delivery Date"),null=True)
    warrenty_date = models.DateField(_("End Warrenty Date"),null=True)
    department = models.ForeignKey(Department, null = True, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, null = True, on_delete=models.CASCADE)
    qr_code = models.ImageField(upload_to='qr_codes', blank=True)



    def __str__(self):
        return self.name
    
    

    def get_absolute_url(self):
        return reverse('equipment-details', kwargs={'pk' : self.pk})    

      

class Procedure(models.Model):
    is_approved = models.BooleanField(_("Is approved by manager"), default=True)
    hospital = models.ForeignKey(Hospital, null = True, on_delete=models.CASCADE)
    physical_condition = models.TextField(_("physical condition"),null=True)
    electrical_safety = models.TextField(_("electrical safety"),null=True)
    preventive_maintenance = models.TextField(_("preventive maintenance "),null=True)
    preformance_testing  = models.TextField(_("preformance testing "),null=True)
    equipment = models.ForeignKey(Equipment,null = True, on_delete=models.CASCADE)


    def __str__(self):
        return self.physical_condition
    
    
    def get_absolute_url(self):
        return reverse('equipment-details', kwargs={'pk' : self.pk})    



###PORT PROXY MODELS INTO NORMAL MODELS, AND USE MULTI INHERITANCE####

class ManagerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.MANAGER)

class EngineerManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.ENGINEER)

class DoctorManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.DOCTOR)



class Notifications(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, null=True, on_delete=models.CASCADE)

class Manager(User):
    objects = ManagerManager()
   
    def __str__(self):
        return self.username
        
class Engineer(User):
    is_approved = models.BooleanField(_("Approved"), default=False)
    current_hospital = models.ForeignKey(Hospital, null=True, on_delete=models.SET_NULL)
    department = models.ManyToManyField(Department)
    is_busy = models.BooleanField(_("Busy"), default=False)
    total_orders = models.IntegerField(_("Total Work Orders"), default=0)
    orders_done = models.IntegerField(_("Total Work Orders Done"), default=0)
    start_time = models.IntegerField(default=0)
    total_response_time = models.DurationField(_("Total_Response Time"), default=datetime.timedelta())
    average_response_time = models.DurationField(_("Average_Response Time"), default=datetime.timedelta())
    objects = EngineerManager()

   
    def __str__(self):
        return self.username

class Doctor(User):
    is_approved = models.BooleanField(_("Approved"), default=False)
    current_hospital = models.ForeignKey(Hospital, null=True, on_delete=models.CASCADE) #should it be cascade?
    objects = DoctorManager()
    
    def __str__(self):
        return self.username

class Company(models.Model):
    name = models.CharField(_("Company Name"), max_length = 225)
    email = models.EmailField(_("Company Email"))
    phone_num = models.CharField(_("Phone Number"), max_length=225)
    hospital = models.ForeignKey(Hospital, null=True, on_delete=models.CASCADE) #should it be cascade?
    

    def __str__(self):
        return self.name
        
class EditedEquipment(models.Model):
    eng = models.ForeignKey(Engineer, null = True, on_delete=models.SET_NULL)
    eq_id = models.IntegerField(_("ID of Equiqment to be Edited"))
    STATUS = (
        ('LIVE', _("LIVE")),
        ('DOWN', _("DOWN"))
    )
    status = models.CharField(_("Equipment Status"), max_length=50, choices=STATUS, default='LIVE')
    name = models.CharField(_("Equipment Name"), max_length = 225) #unique=True
    specs = models.TextField(_("Technical Specifications and Standards"))
    quantity = models.IntegerField()
    serial_num = models.IntegerField()
    manufacturer = models.CharField(_("Manufacturer"), null=True,max_length = 255)
    country = models.CharField(_("Country"), null=True,max_length = 225)
    model = models.CharField(_("Model"), null=True,max_length = 225)
    risk_level = models.CharField(_("Risk Level"), null=True,max_length = 225)
    eq_class = models.CharField(_("class"), null=True,max_length = 225)
    bio_code = models.CharField(_("BioCode"), null=True, max_length = 225)
    med_agent = models.CharField(_("Medical Agent"),null=True, max_length = 225)
    delivery_date = models.DateField(_("Delivery Date"),null=True)
    warrenty_date = models.DateField(_("End Warrenty Date"),null=True)
    department = models.ForeignKey(Department, null = True, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, null = True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm 
from .models import Profile
from authentication.models import User


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ['username', 'email','photo_user']
        widget = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'photo_user': forms.FileInput(attrs={'class':'form-control'}),
        }

dashboard/views.py
from django.shortcuts import render, redirect
from med.models import Manager, Engineer, Doctor
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm


# Create your views here.
def home(request):
    # try : 
        #print(x)   not defind
    #except:
        #print('error')     excute
    try:
        if(request.user.type == 'ENGINEER'):
            eng = Engineer.objects.get(id = request.user.id)
            return render(request, template_name='dashboard/home.html', context={'user' : eng})
        elif(request.user.type == 'DOCTOR'):
            doc = Doctor.objects.get(id = request.user.id)
            return render(request, template_name='dashboard/home.html', context={'user' : doc})
        elif(request.user.type =='MANAGER'):
            man = Manager.objects.get(id = request.user.id)
            return render(request, template_name='dashboard/home.html', context={'user' : man})
    except:
        return render(request, template_name='dashboard/HomePage.html')
    
    
@login_required
def profile(request):
    if(request.user.type == 'ENGINEER'):
        eng = Engineer.objects.get(id = request.user.id)
        return render(request, template_name='dashboard/profile.html', context={'user' : eng})
    elif(request.user.type == 'DOCTOR'):
        doc = Doctor.objects.get(id = request.user.id)
        return render(request, template_name='dashboard/profile.html', context={'user' : doc})
    else:
        return render(request, template_name='dashboard/profile.html')

@login_required
def update_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,request.FILES, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            # messages.success(request, f'Account Info Updated!!')
            return redirect('profile')
        else:
            # messages.faliure(request, f'An error has occured!')
            return redirect('profile')
              
    context = {
            'u_form' : UserUpdateForm(instance=request.user),
        }
    return render(request, "dashboard/update_profile.html", context)  

dashboard/templates/dashboard/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <title>MSM</title>
  <link rel="stylesheet" href="{% static 'dashboard/bootstrap.min.css' %}">
  <link href="{% static 'dashboard/accsess.css' %}" rel="stylesheet">
</head>

<body>
  <!--start navbar-->
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{%url 'home' %}">MSM</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
      data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      {% if user.is_authenticated%}
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
      </li>
      {% endif %}
    </ul>
  </nav>

  <!--start list-->
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="sidebar-sticky pt-3">
          <ul class="nav flex-column">
            {% if user.is_authenticated and user.is_active %}
            {%if user.type == 'MANAGER' %}
            {% if  user.hospital %}
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'welcome' %}">Home</a>
                </li>
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'upload-json' %}">Upload Json</a>
                </li>
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'equipment-list' %}">Medical Equipment</a>
                </li>
    
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'department-list' %}">Departments</a>
                </li>
    
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'list-notifications' %}">Request List</a>
                </li>
    
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'list-employees' %}">View Employees</a>
                </li>
              
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="{% url 'list-tickets' %}">Work Orders</a>
                </li>
                {% else %}
                  <li class="nav-item text-nowrap">
                    <a class="nav-link" href="{% url 'register-hospital'%}">Register Hospital</a>
                  </li>
            {% endif %}
            
            
        {% elif user.type == 'ENGINEER' %}
            {% if  user.in_hospital %}
            
              <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'welcome' %}">Home</a>
              </li>
              <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'equipment-list' %}">Medical Equipment</a>
              </li>
              
              <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'eng-work' %}">My Work</a>
              </li>
            
              <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'list-tickets' %}">Work Orders</a>
              </li>
    
              <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'department-list' %}">Departments</a>
              </li>
    
              <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'add-department' %}">Add Department</a>
              </li>
            {% else %}
              <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'hospital-search'%}">Search for a Hospital</a>
              </li>
            {% endif %}
            
            
        {% elif user.type == 'DOCTOR' %}
            {% if  user.in_hospital %}
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'equipment-list' %}">Medical Equipment</a>
                </li>
    
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'submit-ticket' %}">Submit a Ticket</a>
                </li>
    
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'department-list' %}">Departments</a>
                </li>
              {% else %}
                <li class="nav-item text-nowrap">
                  <a class="nav-link" href="{% url 'hospital-search'%}">Search for a Hospital</a>
                </li>
            {% endif %} 
        {% endif %}
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span> Reports </span>
              <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              {% if user.type == 'ENGINEER' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'list-create-company' %}">
                  <span data-feather="file-text"></span> Connect with companies
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span> Send Mail
                </a>
              </li>
            </ul>
            {% else %}
            <li class="nav-item text-nowrap">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item text-nowrap">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
          </ul>

          
        </div>
      </nav>
      <!--end list-->
    </div>
  </div>



  <!-- Page Content -->
  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

    <!-- Jumbotron Header -->
    <!-- <header class="jumbotron my-4"></header> -->
    {% block content%}{% endblock %}
    <!-- </header> -->
  </main>


  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script>
    window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

</body>

</html>

dashboard/templates/dashboard/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
{% if success %}
{{ user.username }}, your account is confirmed!
{% else %}
Error, invalid token!
{% endif %}
<a href="{% url 'login' %}"><button class='btn btn-primary'>Login Now!</button></a>
</body>
</html>

dashboard/templates/dashboard/home.html
{% extends "dashboard/base.html" %}
{% block content %}
<h2>Welcome {{user.type}} {{user.first_name}} {{user.last_name}}</h2>
{% endblock %}

dashboard/templates/dashboard/mail_body.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email Confirmation</title>
</head>
<body>
<h1>You are almost there, {{ user.username }}!</h1><br>
<h2>Please click <a href="{{ link }}">here</a> to confirm your account</h2>
<h2>The token expires on {{ expiry|time:"TIME_FORMAT" }}</h2>
</body>
</html>

dashboard/templates/dashboard/update_profile.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="from-group">
           <legend class="border-bottom mb-4">Update Profile Info!</legend>
           {{ u_form|crispy }}
        </fieldset>
        <div class="form-group">
           <button class="btn btn-outline-info" type="submit">Update</button>
        </div>

    </form>
</div>
{% endblock content%}

dashboard/templates/dashboard/welcome.html
{% extends "dashboard/base.html" %}

{% block content %}

{% if user.type == 'ENGINEER' %}

<div class="container">
  {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

  <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Total Work Orders</th>
          <th scope="col">Work Orders Done</th>
          <th scope="col">Total Time Response</th>
          <th scope="col">Average Time Response</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ user.first_name }} {{user.last_name}}</td>
          <td>{{ user.total_orders }}</td>
          <td>{{ user.orders_done }}</td>
          <td>{{ user.total_response_time }}</td>
          <td>{{ user.average_response_time }}</td>
        </tr>
      </tbody>
    </table>
</div>
<div class="container">
  <a href="{% url 'eng-work' %}"><button class='btn btn-primary'>View Your Work Orders</button></a>
</div>
{% elif user.type == 'MANAGER' %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Role</th>
      <th scope="col">Email</th>
      <th scope="col">Approve</th>
    </tr>
  </thead>
  <tbody>
    {% for request in user.hospital.notifications_set.all %}
    <tr>
      <td>{{ request.id }}</td>
      <td>{{ request.user.first_name }} {{ request.user.last_name }}</td>
      <td> {{ request.user.type}}</td>
      <td> {{ request.user.email}}</td>
      <td><a href="{% url 'join-hospital' request.user.id %}"><button class="btn btn-primary">Approve</button></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if user.type == 'MANAGER' %}
<h2>Equipment Modifications</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Submited by</th>
      <th scope="col">Email</th>
      <th scope="col">Equipment</th>
      <th scope="col">Department</th>
      <th scope="col">Details</th>
      <th scope="col">Approve</th>
    </tr>
  </thead>
  <tbody>
    {% for equip in user.hospital.editedequipment_set.all %}
    <tr>
      <td>{{ equip.eq_id }}</td>
      <td>{{ equip.eng.first_name }} {{ equip.eng.last_name }}</td>
      <td>{{ equip.eng.email }}</td>
      <td>{{ equip.name }}</td>
      <td> {{ equip.department.name }}</td>
      <td><a href="{% url 'edited-equipment-details' equip.id %}"><button class="btn btn-primary">View Details</button></a></td>
      <td><a href="{% url 'update-edited-equipment' equip.id %}"><button class="btn btn-primary">Approve</button></a></td>    </tr>
    {% endfor %}
  </tbody>
</table>

<h2>Equipment Addition</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Equipment Name</th>
      <th scope="col">Department Name</th>
      <th scope="col">Details</th>
      <th scope="col">Approve</th>
    </tr>
  </thead>
  <tbody>
    {% for equip in user.hospital.equipment_set.all %}
      {% if not equip.is_approved %}
        <tr>
          <td>{{ equip.id }}</td>
          <td>{{ equip.name }}</td>
          <td>{{ equip.department.name }}</td>
          <td><a href="{% url 'pre-approved-equipment-details' equip.id %}"><button class="btn btn-primary">Details</button></a></td>
          <td><a href="{% url 'approve_added_equipment' equip.id %}"><button class="btn btn-primary">Approve</button></a></td>
        </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>
<h2>Procedure Addition</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">physical_condition</th>
      <th scope="col">electrical_safety</th>
      <th scope="col">preventive_maintenance</th>
      <th scope="col">preformance_testing</th>
      <th scope="col">Approve</th>
    </tr>
  </thead>
  <tbody>
    {% for procedure in user.hospital.equipment_set.all %}
      {% if not procedure.is_approved %}
        <tr>
          <td>{{ procedure.id }}</td>
          <td>{{ procedure.physical_condition }}</td>
          <td>{{ procedure.electrical_safety}}</td>
          <td>{{ procedure.preventive_maintenance}}</td>
          <td>{{ procedure.preformance_testing}}</td>
          <td><a href="{% url 'approve_added_procedure' procedure.id %}"><button class="btn btn-primary">Approve</button></a></td>
        </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>

{% endif %}

{% endblock %}